#! /bin/sh

SED="/usr/bin/sed"
prefix="/home/cyberboy/php-arm64-rootfs/php"
datarootdir="/home/cyberboy/php-arm64-rootfs/php/php"
exec_prefix="${prefix}"
version="8.3.5"
vernum="80305"
include_dir="${prefix}/include/php"
includes="-I$include_dir -I$include_dir/main -I$include_dir/TSRM -I$include_dir/Zend -I$include_dir/ext -I$include_dir/ext/date/lib"
ldflags=" -L/home/cyberboy/php-arm64-rootfs/onig/lib"
libs="  -lrt -lm  -lonig "
extension_dir='/home/cyberboy/php-arm64-rootfs/php/lib/php/extensions/no-debug-non-zts-20230831'
man_dir=`eval echo ${datarootdir}/man`
program_prefix=""
program_suffix=""
exe_extension=""
php_cli_binary=NONE
php_cgi_binary=NONE
configure_options=" '--host=aarch64-none-linux-gnu' '--prefix=/home/cyberboy/php-arm64-rootfs/php' 'AR=/opt/codesourcery/bin/aarch64-none-linux-gnu-ar' 'RANLIB=/opt/codesourcery/bin/aarch64-none-linux-gnu-ranlib' '--disable-all' '--enable-cgi' '--enable-session' '--enable-mbstring' '--enable-json' '--enable-sockets' 'host_alias=aarch64-none-linux-gnu' 'ONIG_CFLAGS=-I/home/cyberboy/php-arm64-rootfs/onig/include' 'ONIG_LIBS=-L/home/cyberboy/php-arm64-rootfs/onig/lib -lonig'"
php_sapis=" cli phpdbg cgi"
ini_dir=""
ini_path="/home/cyberboy/php-arm64-rootfs/php/lib"

# Set php_cli_binary and php_cgi_binary if available
for sapi in $php_sapis; do
  case $sapi in
  cli)
    php_cli_binary="${exec_prefix}/bin/${program_prefix}php${program_suffix}${exe_extension}"
    ;;
  cgi)
    php_cgi_binary="${exec_prefix}/bin/${program_prefix}php-cgi${program_suffix}${exe_extension}"
    ;;
  esac
done

# Determine which (if any) php binary is available
if test "$php_cli_binary" != "NONE"; then
  php_binary="$php_cli_binary"
else
  php_binary="$php_cgi_binary"
fi

# Remove quotes
configure_options=`echo $configure_options | $SED -e "s#'##g"`

case "$1" in
--prefix)
  echo $prefix;;
--includes)
  echo $includes;;
--ldflags)
  echo $ldflags;;
--libs)
  echo $libs;;
--extension-dir)
  echo $extension_dir;;
--include-dir)
  echo $include_dir;;
--php-binary)
  echo $php_binary;;
--php-sapis)
  echo $php_sapis;;
--configure-options)
  echo $configure_options;;
--man-dir)
  echo $man_dir;;
--ini-path)
  echo $ini_path;;
--ini-dir)
  echo $ini_dir;;
--version)
  echo $version;;
--vernum)
  echo $vernum;;
*)
  cat << EOF
Usage: $0 [OPTION]
Options:
  --prefix            [$prefix]
  --includes          [$includes]
  --ldflags           [$ldflags]
  --libs              [$libs]
  --extension-dir     [$extension_dir]
  --include-dir       [$include_dir]
  --man-dir           [$man_dir]
  --php-binary        [$php_binary]
  --php-sapis         [$php_sapis]
  --ini-path          [$ini_path]
  --ini-dir           [$ini_dir]
  --configure-options [$configure_options]
  --version           [$version]
  --vernum            [$vernum]
EOF
  exit 1;;
esac

exit 0
